[build]
  command = "yarn prisma:fmt && yarn prisma:validate && yarn prisma:gen && yarn prisma:dev && yarn prisma:deploy && yarn prisma:push && yarn run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["node_modules/.prisma/client/**"]