[build]
  command = "yarn add --frozen-lockfile && yarn build"
  publish = ".next" # adapter will rewrite as needed

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
  included_files = ["node_modules/.prisma/client/**"]